Bluetooth-Scanner:
  environment:
    EULA: ${EULA}
    VERSION: ${VERSION}
    DIFFICULTY: ${DIFFICULTY}
    MODE: ${MODE}
    PVP: ${PVP}
    WHITELIST: ${WHITELIST}
    OPS: ${OPS}
    MOTD: ${MOTD}
    SEED: ${SEED}
    WORLD: ${WORLD}
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
